norm_diff_threshold: 0.35
heatmap_vis_upper_bound: 0.75
blend_weight_original_image: 0.3
randomize_images: True
randomize_scene: False
same_object: True
different_objects: False
multiple_object: False # sample from multi object scenes
kernel_variance: 0.25
networks:
# - "caterpillar_Resnet34_8s_atten_fuse_M_background_0.500_3_no_flip_new"
# - "caterpillar_Resnet34_8s_fuse_M_background_0.500_3_no_flip_new"
 - "caterpillar_Resnet34_8s_M_background_0.500_3"
# - "caterpillar_Resnet34_8s_cat_fuse_M_background_0.500_3_no_flip_new"


norm_diff_threshold_dict:
  hats_consistent_M_background_0.500_3:
    0.25
  hats_specific_M_background_2.000_9:
    0.35
  shoes_specific_M_background_2.000_6_with_synthetic:
    0.35