norm_diff_threshold: 0.35
heatmap_vis_upper_bound: 0.75
blend_weight_original_image: 0.3
randomize_images: True
randomize_scene: False
same_object: True
different_objects: False
multiple_object: False # sample from multi object scenes
kernel_variance: 0.25
networks:
- "0.5_3_no"
- "0.5_3_fuse_add"
- "0.5_3_fuse_cat"
- "0.5_3_fuse_atten"
- "0.5_3_FuseNet"


norm_diff_threshold_dict:
  hats_consistent_M_background_0.500_3:
    0.25
  hats_specific_M_background_2.000_9:
    0.35
  shoes_specific_M_background_2.000_6_with_synthetic:
    0.35