params:
  num_image_pairs: 25
  num_matches_per_image_pair: 100

networks:
  20220306-214801_3d:
    path_to_network_params: trained_models/20220306-214801_3d/006000.pth

dataset: [] # which dataset to use, not used for now

output_dir: analysis